apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: ml-kubernetes-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ml-kubernetes-api
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70