apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-kubernetes-api-config
data:
  # Logic Configs
  LOGIC_MD_00001_ENDPOINT: "http://ml-kubernetes-logic-md00001-green:5000"
  LOGIC_MD_00002_ENDPOINT: "http://ml-kubernetes-logic-md00002-green:5000"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-kubernetes-api-green-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-kubernetes-green-api
  template:
    metadata:
      labels:
        app: ml-kubernetes-green-api
    spec:
      containers:
      - image: tanawitp/ml-kubernetes-api
        name: ml-kubernetes-api
        ports:
        - containerPort: 5000
        envFrom:
          - configMapRef:
              name: ml-kubernetes-api-config

---

apiVersion: v1
kind: Service
metadata:
  name: ml-kubernetes-green-api
spec:
  type: LoadBalancer
  ports:
  - port: 50000
    targetPort: 5000
  selector:
    app: ml-kubernetes-green-api

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: ml-kubernetes-api-green-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ml-kubernetes-green-api
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70
