apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-kubernetes-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-kubernetes-api
  template:
    metadata:
      labels:
        app: ml-kubernetes-api
    spec:
      containers:
      - image: tanawitp/ml-kubernetes-api
        name: ml-kubernetes-api
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: ml-kubernetes-api
spec:
  type: LoadBalancer
  ports:
  - port: 50000
    targetPort: 5000
  selector:
    app: ml-kubernetes-api

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: ml-kubernetes-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ml-kubernetes-api
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70